var material = [
  {
    id: '00001',
    lang1: 'el aeropuerto',
    lang2: 'the airport',
    lang3: 'der Flughafen',
  },
  {
    id: '00002',
    lang1: 'los aeropuertos',
    lang2: 'the airports',
    lang3: 'die Flughäfen',
  },
  {
    id: '00003',
    lang1: 'el avión',
    lang2: 'the airplane',
    lang3: 'das Flugzeug',
  },
  {
    id: '00004',
    lang1: 'los aviones',
    lang2: 'the airplanes',
    lang3: 'die Flugzeuge',
  },
  {
    id: '00005',
    lang1: 'la bicicleta',
    lang2: 'the bicycle',
    lang3: 'das Fahrrad',
  },
  {
    id: '00006',
    lang1: 'las bicicletas',
    lang2: 'the bicycles',
    lang3: 'die Fahrräder',
  },
  { id: '00007', lang1: 'el tren', lang2: 'the train', lang3: 'der Zug' },
  { id: '00008', lang1: 'trenes', lang2: 'the trains', lang3: 'die Züge' },
  { id: '00009', lang1: 'el coche', lang2: 'the car', lang3: 'das Auto' },
  { id: '00010', lang1: 'los coches', lang2: 'the cars', lang3: 'die Autos' },
  { id: '00011', lang1: 'ser', lang2: 'to be', lang3: 'sein' },
  { id: '00012', lang1: 'tener', lang2: 'to have', lang3: 'haben' },
  { id: '00013', lang1: 'ser capaz de', lang2: 'to be able', lang3: 'können' },
  { id: '00014', lang1: 'desear', lang2: 'to want', lang3: 'wollen' },
  { id: '00015', lang1: 'ir', lang2: 'to go', lang3: 'gehen' },
  { id: '00016', lang1: 'dormirir', lang2: 'to sleep', lang3: 'schlafen' },
  { id: '00017', lang1: 'aprender', lang2: 'to learn', lang3: 'lernen' },
  { id: '00018', lang1: 'quisiera', lang2: 'i want', lang3: 'ich möchte' },
  { id: '00019', lang1: 'puedo', lang2: 'i can', lang3: 'ich kann' },
  { id: '00020', lang1: 'cómo', lang2: 'how', lang3: 'wie' },
  { id: '00021', lang1: 'quién', lang2: 'who', lang3: 'wer' },
  { id: '00022', lang1: 'qué', lang2: 'what', lang3: 'was' },
  { id: '00023', lang1: 'por qué', lang2: 'why', lang3: 'warum' },
  { id: '00024', lang1: 'dónde', lang2: 'where', lang3: 'wo' },
  { id: '00025', lang1: 'amigo', lang2: 'friend', lang3: 'Freund' },
  { id: '00026', lang1: 'tren', lang2: 'train', lang3: 'Zug' },
  {
    id: '00027',
    lang1: 'Podría usted ayudarme?',
    lang2: 'Could you help me please?',
    lang3: 'Können Sie mir bitte helfen?',
  },
  { id: '00028', lang1: 'el barco', lang2: 'the ship', lang3: 'das Schiff' },
  {
    id: '00029',
    lang1: 'los barcos',
    lang2: 'the ships',
    lang3: 'die Schiffe',
  },
  { id: '00030', lang1: 'el autobús', lang2: 'the bus', lang3: 'der Bus' },
  { id: '00031', lang1: 'los buses', lang2: 'the busses', lang3: 'die Busse' },
  {
    id: '00032',
    lang1: 'Buenos días',
    lang2: 'good morning',
    lang3: 'Guten Morgen',
  },
  {
    id: '00033',
    lang1: 'Buenos días (form.)',
    lang2: 'Hello (form.)',
    lang3: 'Guten Tag',
  },
  {
    id: '00034',
    lang1: 'Buenas noches',
    lang2: 'good evening',
    lang3: 'Guten Abend',
  },
  {
    id: '00035',
    lang1: 'Buenas noches',
    lang2: 'good night',
    lang3: 'Gute Nacht',
  },
  { id: '00036', lang1: 'Adíos', lang2: 'Good bye', lang3: 'Auf Wiedersehen' },
  {
    id: '00037',
    lang1: 'me llamo Karoll',
    lang2: 'i am Karoll / my name is Karoll',
    lang3: 'ich bin Karoll',
    lang3Option2: 'ich heiße Karoll',
    lang3Option3: 'mein Name ist Karoll',
  },
  {
    id: '00038',
    lang1: 'de dónde es',
    lang2: 'where are you from?',
    lang3: 'woher kommst du?',
  },
  {
    id: '00039',
    lang1: 'Soy de Colombia',
    lang2: 'i am from Colombia',
    lang3: 'ich komme aus Kolumbien',
  },
  { id: '00040', lang1: 'el país', lang2: 'the country', lang3: 'das Land' },
  { id: '00041', lang1: 'Alemania', lang2: 'Germany', lang3: 'Deutschland' },
  { id: '00042', lang1: 'Austria', lang2: 'Austria', lang3: 'Österreich' },
  { id: '00043', lang1: 'Suiza', lang2: 'Switzerland', lang3: 'Schweiz' },
  {
    id: '00044',
    lang1: 'el apellido',
    lang2: 'the lastname',
    lang3: 'der Nachname',
  },
  {
    id: '00045',
    lang1: 'el primer nombre',
    lang2: 'the firstname',
    lang3: 'der Vorname',
  },
  {
    id: '00046',
    lang1: 'deletrear',
    lang2: 'to spell',
    lang3: 'buchstabieren',
  },
  { id: '00047', lang1: 'también', lang2: 'also', lang3: 'auch' },
  {
    id: '00048',
    lang1: 'puedes repetir?',
    lang2: 'can you repeat that?',
    lang3: 'kannst du das wiederholen?',
  },
  {
    id: '00049',
    lang1: 'no entiendo',
    lang2: 'i don´t understand',
    lang3: 'ich verstehe nicht',
  },
  {
    id: '00050',
    lang1: 'aprendo alemán',
    lang2: 'i learn german',
    lang3: 'ich lerne Deutsch',
  },
  {
    id: '00051',
    lang1: 'el arquitecto',
    lang2: 'the architect',
    lang3: 'der Architekt',
    lang3Option2: 'die Architektin',
  },
  {
    id: '00052',
    lang1: 'el medico',
    lang2: 'the doctor',
    lang3: 'der Arzt',
    lang3Option2: 'die Ärztin',
  },
  {
    id: '00053',
    lang1: 'el maestro',
    lang2: 'the teacher',
    lang3: 'der Lehrer',
    lang3Option2: 'die Lehrerin',
  },
  {
    id: '00054',
    lang1: 'la actriz',
    lang2: 'the actor',
    lang3: 'die Schauspielerin',
  },
  {
    id: '00055',
    lang1: 'el actor',
    lang2: 'the actor',
    lang3: 'der Schauspieler',
  },
  {
    id: '00056',
    lang1: 'la secretaria',
    lang2: 'the secretary',
    lang3: 'die Sekretärin',
  },
  {
    id: '00057',
    lang1: 'la vendedora',
    lang2: 'the saleswoman',
    lang3: 'die Verkäuferin',
  },
  {
    id: '00058',
    lang1: 'el vendedor',
    lang2: 'the seller',
    lang3: 'der Verkäufer',
  },
  {
    id: '00059',
    lang1: 'el especialista en IT',
    lang2: 'IT specialist',
    lang3: 'der IT-Spezialist',
    lang3Option2: 'die IT-Spezialistin',
  },
  {
    id: '00060',
    lang1: 'el periodista',
    lang2: 'the journalist',
    lang3: 'der Journalist',
    lang3Options: 'die Journalistin',
  },
  {
    id: '00061',
    lang1: 'el estudiante',
    lang2: 'the student',
    lang3: 'der Student',
    lang3Option2: 'die Studentin',
  },
  {
    id: '00062',
    lang1: 'el empleador',
    lang2: 'the employer',
    lang3: 'der Arbeitgeber',
  },
  {
    id: '00063',
    lang1: 'capacitatión',
    lang2: 'the training',
    lang3: 'die Ausbildung',
  },
  {
    id: '00064',
    lang1: 'la profesión',
    lang2: 'the profession',
    lang3: 'der Beruf',
  },
  {
    id: '00065',
    lang1: 'la universidad',
    lang2: 'the university',
    lang3: 'die Universität',
    lang3Option2: 'die Hochschule',
  },
  {
    id: '00066',
    lang1: 'la pasantía',
    lang2: 'the internship',
    lang3: 'das Praktikum',
  },
  {
    id: '00067',
    lang1: 'la escuela',
    lang2: 'the school',
    lang3: 'die Schule',
  },
  { id: '00068', lang1: 'trabajar', lang2: 'to work', lang3: 'arbeiten' },
  { id: '00069', lang1: 'estudiar', lang2: 'to study', lang3: 'studieren' },
  {
    id: '00070',
    lang1: 'desempleados',
    lang2: 'unemployed',
    lang3: 'arbeitslos',
  },
  { id: '00071', lang1: 'ingeniero', lang2: 'engineer', lang3: 'Ingenieur' },
  {
    id: '00072',
    lang1: 'el camarero',
    lang2: 'the waiter',
    lang3: 'der Kellner',
  },
  {
    id: '00073',
    lang1: 'la enfermera',
    lang2: 'the nurse',
    lang3: 'die Krankenschwester',
  },
  { id: '00074', lang1: 'años', lang2: 'the age', lang3: 'das Alter' },
  {
    id: '00075',
    lang1: '',
    lang2: 'i go to my relatives',
    lang3: 'ich fahre zu meinen Verwandten',
  },
  {
    id: '00076',
    lang1: '',
    lang2: 'to take the elevator',
    lang3: 'den Aufzug nehmen',
  },
  { id: '00077', lang1: '', lang2: 'the traveller (f)', lang3: 'die Reisende' },
  { id: '00078', lang1: '', lang2: 'shall / should', lang3: 'sollen' },
  { id: '00079', lang1: '', lang2: 'to stay', lang3: 'bleiben' },
  { id: '00080', lang1: '', lang2: 'immediately', lang3: 'sofort' },
  { id: '00081', lang1: '', lang2: 'the counter', lang3: 'der Schalter' },
  {
    id: '00082',
    lang1: '',
    lang2: 'we proceed',
    lang3: 'wir machen Fortschritte',
  },
  { id: '00083', lang1: 'feliz', lang2: 'happy', lang3: 'glücklich' },
  {
    id: '00084',
    lang1: 'el boleto / el tiquete',
    lang2: 'the ticket',
    lang3: 'der Fahrschein',
  },
  { id: '00085', lang1: 'el vía', lang2: 'the track', lang3: 'das Gleis' },
  {
    id: '00086',
    lang1: '',
    lang2: 'the main station',
    lang3: 'der Hauptbahnhof',
  },
  {
    id: '00087',
    lang1: 'creo que',
    lang2: 'i believe that',
    lang3: 'ich glaube, dass',
  },
  {
    id: '00088',
    lang1: 'a qué hora?',
    lang2: 'when?',
    lang3: 'um wie viel Uhr?',
  },
  { id: '00089', lang1: '', lang2: 'the attachment', lang3: 'die Anhaftung' },
  { id: '00090', lang1: '', lang2: 'the desire', lang3: 'die Begierde' },
  { id: '00091', lang1: '', lang2: 'the jealousy', lang3: 'die Eifersucht' },
  { id: '00092', lang1: '', lang2: 'the pride', lang3: 'der Stolz' },
  { id: '00093', lang1: '', lang2: 'the ignorance', lang3: 'die Unwissenheit' },
  { id: '00094', lang1: '', lang2: 'the anger', lang3: 'der Zorn' },
  { id: '00095', lang1: '', lang2: 'the confusion', lang3: 'die Verwirrung' },
  { id: '00096', lang1: '', lang2: 'the compassion', lang3: 'das Mitgefühl' },
  {
    id: '00097',
    lang1: '',
    lang2: 'the fearlessness',
    lang3: 'die Furchtlosigkeit',
  },
  { id: '00098', lang1: '', lang2: 'the love', lang3: 'die Liebe' },
  { id: '00099', lang1: '', lang2: 'the merit', lang3: 'der Verdienst' },
  { id: '00100', lang1: '', lang2: 'the wisdom', lang3: 'die Weisheit' },
  { id: '00101', lang1: '', lang2: 'the teachings', lang3: 'die Lehren' },
  { id: '00102', lang1: '', lang2: 'realized', lang3: 'verwirklicht' },
  {
    id: '00103',
    lang1: '',
    lang2: 'the teacher',
    lang3: 'der Lehrer',
    lang3Option2: 'die Lehrerin',
  },
  { id: '00104', lang1: '', lang2: 'the protector', lang3: 'der Schützer' },
  {
    id: '00105',
    lang1: '',
    lang2: 'the protectors (pl)',
    lang3: 'die Schützer',
  },
  {
    id: '00106',
    lang1: '',
    lang2: 'the four noble truths',
    lang3: 'die vier edlen Wahrheiten',
  },
  {
    id: '00107',
    lang1: '',
    lang2: 'the accumulation of merit',
    lang3: 'die Ansammlung von Verdienst',
  },
  {
    id: '00108',
    lang1: '',
    lang2: 'cause and effect',
    lang3: 'Ursache und Wirkung',
  },
  { id: '00109', lang1: '', lang2: 'the behaviour', lang3: 'das Verhalten' },
  { id: '00110', lang1: '', lang2: 'the emptiness', lang3: 'die Leerheit' },
  { id: '00111', lang1: '', lang2: 'the attitude', lang3: 'die Einstellung' },
  { id: '00112', lang1: '', lang2: 'the view', lang3: 'die Sicht' },
  { id: '00113', lang1: '', lang2: 'the joy', lang3: 'die Freude' },
  {
    id: '00114',
    lang1: '',
    lang2: 'the sympathetic joy / rejoice',
    lang3: 'die Mitfreude',
  },
  { id: '00115', lang1: '', lang2: 'the equanimity', lang3: 'der Gleichmut' },
  { id: '00116', lang1: '', lang2: 'the suffering', lang3: 'das Leiden' },
  { id: '00117', lang1: '', lang2: 'the truth', lang3: 'die Wahrheit' },
  { id: '00118', lang1: '', lang2: 'the path', lang3: 'der Weg' },
  {
    id: '00119',
    lang1: '',
    lang2: 'the initiation / empowerment',
    lang3: 'die Einweihung',
  },
  {
    id: '00120',
    lang1: '',
    lang2: 'the one-pointedness',
    lang3: 'die Einsgerichtetheit',
  },
  {
    id: '00121',
    lang1: '',
    lang2: 'composite (adj)',
    lang3: 'zusammengesetzt',
  },
  { id: '00122', lang1: '', lang2: 'impermanent (adj)', lang3: 'vergänglich' },
  { id: '00123', lang1: '', lang2: 'the change', lang3: 'die Veränderung' },
  {
    id: '00124',
    lang1: '',
    lang2: 'the phenomena (pl)',
    lang3: 'die Phänomene',
  },
  { id: '00125', lang1: '', lang2: 'the peace', lang3: 'der Frieden' },
  { id: '00126', lang1: '', lang2: 'the liberation', lang3: 'die Befreiung' },
  {
    id: '00127',
    lang1: '',
    lang2: 'the enlightenment',
    lang3: 'die Erleuchtung',
  },
  { id: '00128', lang1: '', lang2: 'the equality', lang3: 'die Gleichheit' },
  { id: '00129', lang1: '', lang2: 'the experience', lang3: 'die Erfahrung' },
  {
    id: '00130',
    lang1: '',
    lang2: 'the conciousness',
    lang3: 'das Bewusstsein',
  },
  {
    id: '00131',
    lang1: '',
    lang2: 'the accumulation',
    lang3: 'die Ansammlung',
  },
  {
    id: '00132',
    lang1: '',
    lang2: 'the generosity',
    lang3: 'die Großzügigkeit',
  },
  { id: '00133', lang1: '', lang2: 'the patience', lang3: 'die Geduld' },
  // Dharma-Wörterbuch bis S. 8 Mitta
  { id: '00134', lang1: '', lang2: '', lang3: '' },
  { id: '00135', lang1: '', lang2: '', lang3: '' },
  { id: '00136', lang1: '', lang2: '', lang3: '' },
  { id: '00137', lang1: '', lang2: '', lang3: '' },
  { id: '00138', lang1: '', lang2: '', lang3: '' },
  { id: '00139', lang1: '', lang2: '', lang3: '' },
  { id: '00140', lang1: '', lang2: '', lang3: '' },
];
